# Generated by Django 4.2.2 on 2023-07-06 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0013_alter_tracker_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='present',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
        ),
    ]
